apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: huis-helden-ingress
  namespace: huis-helden
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - huis-helden.nl
        - www.huis-helden.nl
      secretName: huis-helden-tls
  rules:
    - host: huis-helden.nl
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
    - host: www.huis-helden.nl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
